# API网关开发环境配置
server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        - id: config-center
          uri: http://localhost:8888
          predicates:
            - Path=/config/**
        - id: user-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/users/**
        - id: business-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/business/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"