server:
  port: 8888

spring:
  application:
    name: platform-config-center
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/platform/config-repo.git
          default-label: main
          timeout: 10
          clone-on-start: true
        health:
          repositories:
            git:
              enabled: true
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    user:
      name: admin
      password: admin123

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    bus-refresh:
      enabled: true

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.security: DEBUG